name: CI/CD Pipeline
on:
  push:
    branches:
      - master  # Trigger on push to the master branch
  pull_request:
    branches:
      - master  # Trigger on pull requests to the master branch
  schedule:
    - cron: '0 0 * * *'  # Run nightly at midnight UTC
jobs:
  test:
    runs-on: ubuntu-latest  # Use Ubuntu runner, you can use windows-latest too if needed

    steps:
      # Checkout code from GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest

      # Run flake8 for code quality checks
      - name: Run flake8
        run: flake8 .

      # Run pytest for testing
      - name: Run pytest
        run: pytest

  build:
    runs-on: ubuntu-latest  # Use Ubuntu runner for the build job

    steps:
      # Checkout code from GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t flask-docker-app .

      # Run the Docker container
      - name: Run Docker container
        run: |
          docker run -d -p 5000:5000 flask-docker-app
